#configuration for running standalone application, not as a mircoservice

spring.jpa.hibernate.ddl-auto:
  validate
spring.jpa.hibernate.naming_strategy:
  org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.database:
  H2
spring.jpa.show-sql: 
  true

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

localeureka:
  http://localhost:8761
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-server.credentials.uri:${localeureka}}/eureka/
 
# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.application_uris[0]}
    nonSecurePort: 80
---