#configuration for running standalone application, not as a mircoservice
#---
#spring:
#    profiles: default
#spring.jpa.hibernate.ddl-auto:
#  validate
#spring.jpa.hibernate.naming_strategy:
#  org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.database:
#  H2
#spring.jpa.show-sql: 
#  true
#spring.datasource.schema:
#  classpath:testdb/schema.sql
#spring.datasource.data:
#  classpath:testdb/data.sql
#---